language: node_js
node_js:
  - "0.10"
  - "0.11"
before_install:
  - "npm install -g karma-cli"
before_script:
  - "npm install -g karma-cli gulp@3.6.2"
  - "./node_modules/.bin/gulp build"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
